language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

install: true

go_import_path: github.com/xdefrag/hash-ketchum

services:
  - redis-server

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379

install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip -d protoc
  - export PATH=$PATH:$PWD/protoc/bin/
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get github.com/golang/mock/gomock
  - go install github.com/golang/mock/mockgen
